### ISSUE TITLE
Integrate sbt-org-policies

### ISSUE THREAD

**Issue by raulraja** [47deg/iota#3]

**Comment by andyscott** [comment]
If possible, I would prefer we do source formatting by hand. The code isn't super long but it's mostly unusual macro/type code. AFAIK formatters don't do terribly with with that stuff 😦.

**Comment by juanpedromoreno** [comment]
Before doing this, is this PR ready to merge https://github.com/47deg/iota/pull/2? @andyscott @raulraja

**Comment by andyscott** [comment]
Almost. I'm rebasing/cleaning it up now!

**Comment by juanpedromoreno** [comment]
Nice, thanks!
